### PR TITLE
feat: introduced new nuxt module (experimental)

### PR DESCRIPTION
**Pull request by ennioVisco**
This PR enhances the nuxt module to include the following features:

- Introduces a new playground to test the module locally
- Changes the configuration key to make it more in line with `nuxt` camelCase standard
- Allows to define the configs globally
- Provides the configuration as an injected global variable, for easy access in components
- Auto-installs the required packages (wagmi and viem), inline with how nuxt modules usually work

Since the module is still experimental, it is currently added as an extra one, and should at some point replace the previous one.

I hope this work is appreciated, it was a lot of fun for me, and I strongly support the development of this project :)

### CODE REVIEW

**Comment by unicape** [comment]
I think this is more bloated. The original intention of `@use-wagmi/nuxt` is just to provide automatic import.

**Comment by ennioVisco** [comment]
I understand your concern. 
But this is not how nuxt modules usually work and it can mislead the users.

I will try to unbloat it a bit more in the upcoming days

**Comment by unicape** [comment]
I would even like to remove the '@use-wagmi/nuxt' package and use 'unplugin-vue-components' instead

And I don't think it's a good idea to configure 'wagmi' in the 'nuxt.config.ts' file

**Comment by ennioVisco** [comment]
> I would even like to remove the '@use-wagmi/nuxt' package and use 'unplugin-vue-components' instead

There is a native `addImportsDir` ([see here](https://nuxt.com/docs/api/kit/autoimports#addimportsdir)) that perhaps can fit the purpose, but I didn't want to change too much of your code

> And I don't think it's a good idea to configure 'wagmi' in the 'nuxt.config.ts' file

I also didn't love it tbh, but the problem when using `use-wagmi` in nuxt is the following:

The code: 
```ts
import { UseWagmiPlugin } from 'use-wagmi'

app.use(UseWagmiPlugin, { config })
```
and the code:
```ts
import { VueQueryPlugin } from "@tanstack/vue-query"

app.use(VueQueryPlugin)
```
And namely all the code that changes the vue instance, is usually put in a plugin at the start of the nuxt app (see https://nuxt.com/docs/guide/directory-structure/plugins#vue-plugins).

This means that, either the user of `use-wagmi` adds a plugins in `plugins/wagmi.ts` that does exactly that, or we do it for them. Note also that the config parameter is optional, if people want to just use auto-imports they can leave it empty.

If you have other ideas to do it easily, I'm open to suggestions

**Comment by unicape** [comment]
> This means that, either the user of use-wagmi adds a plugins in plugins/wagmi.ts that does exactly that, or we do it for them. Note also that the config parameter is optional, if people want to just use auto-imports they can leave it empty.

This is where 'plugins' exist to do just that

**Comment by ennioVisco** [comment]
Perhaps another option could be to have a composable like:

```ts
useWagmi({

} as CreateConfigParameters)
```
that automatically adds the vue plugins, but only if the user actually calls it. Would it be better for you?

**Comment by unicape** [comment]
If all plugins do this, the nuxt.config.ts file will be difficult to maintain

**Comment by unicape** [comment]
I'm still sticking to the '@use-wagmi/nuxt' package and simply importing it automatically. Thank you very much for your contribution

**Comment by ennioVisco** [comment]
> If all plugins do this, the nuxt.config.ts file will be difficult to maintain

The composable idea is alternative to the `nuxt.config.ts` change. I'll propose a new PR in the upcoming days and we can discuss there. Thanks a lot for your time :)

**Pull request closed without merging**
