### PR TITLE
refactor: use @nuxt/module-builder

### PR DESCRIPTION
**Pull request by Hebilicious**
Changes to the build system and the exports fields of the package.json to use @nuxt/module-builder instead of tsup.
This will allow the module to be listed in nuxt.com/modules, as it will properly generate everything that is needed.

Note that nuxt-module-build uses unbuild under the hood, and that proper support for cts/mts will be added with the next release (https://github.com/unjs/unbuild/releases/tag/v2.0.0-rc.0)
Therefore in the next release of `nuxt-module-build`, there won't be a warning anymore while building the project.

I'm happy to submit the module there https://github.com/nuxt/modules

I also wanted to ask you if you had the chance to talk to the viem/wagmi maintainers to make this module official @unicape ?

### CODE REVIEW

**Comment by unicape** [comment]
@Hebilicious I wonder if it supports nuxt bridge

**Comment by unicape** [comment]
@Hebilicious Yes, because the wagmi team does not have time to conduct code reviews, so currently use-wagmi exists as a separate warehouse. I will try to contact the wagmi team after the wagmi v2 version

**Comment by Hebilicious** [comment]
@unicape what else do you need to merge this ?
For nuxt bridge support I don't think it matters too much, but I'd assume it works.

**Comment by unicape** [comment]
@Hebilicious alright, thank you very much

**Pull request merged**
